version: '3.8'

services:
  dev:
    container_name: route-app-fe
    image: route-app-fe:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn run start
    ports:
      - 3000:3000
      - 9000:9000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped



      